### ISSUE TITLE
Volume key bug

### ISSUE THREAD

**Issue by ThePrimalPea** [RabahX/YT-ReVanced-Module#11]
18.10.37 have volume key bug which will spam these lines like this infinitely during the install process.

![Volume Key Bug](https://user-images.githubusercontent.com/92656767/226780743-abc5d39c-0a8d-4ea8-baf5-49a547187989.png)

**Comment by RabehX** [comment]
Fixed , try NOW !

**Comment by ThePrimalPea** [comment]
Fixed
