### ISSUE TITLE
Proper credits to the Revanced Extended

### ISSUE THREAD

**Issue by amogus07** [RabahX/YT-ReVanced-Module#13]
I believe the apk you provide with the module has been patched using Revanced Extended. Lots of people are sharing patched apks and modules on various website without proper credit which has already done damage to the original project, but in my opinion, your module is unique and has a reason to exist because from my experience, it's more reliable than all other methods of installing RVX I've tried so far. So, to support the upstream project your module is dependent on, please add a link to [inotia00's Github repository](https://github.com/inotia00) to readme.md.

**Comment by RabehX** [comment]
Done
