### ISSUE TITLE
Crashes on 18.3.33

### ISSUE THREAD

**Issue by ThePrimalPea** [RabahX/YT-ReVanced-Module#2]
Updated my YouTube to version 18.3.33 and flashed the module. Then after rebooted, the YouTube keep crashing.

Minor bug (existed since 18.3.32): double tap to skip 10 seconds of video in full screen won't work while playing video but rewind 10 seconds still. The only way to skip it is tap one time in the video while it playing to show up button layout, then you can double tap to skip it.

**Comment by RabehX** [comment]
I will Update Module Tomorrow and you're use Material You theme ?

**Comment by ThePrimalPea** [comment]
Yeah

**Comment by RabehX** [comment]
try last version and answer me

**Comment by ThePrimalPea** [comment]
It worked, no more crashing. But the minor bug i mentioned above haven't fixed

**Comment by RabehX** [comment]
Unfortunately I can't fix it because it's from the source
