### ISSUE TITLE
Bug: YouTube won't detach

### ISSUE THREAD

**Issue by ThePrimalPea** [RabahX/YT-ReVanced-Module#8]
After flashed the module, YouTube still in the update list of Play Store
Version: 18.7.33

**Comment by RabehX** [comment]
i will fix it

**Comment by RabehX** [comment]
Test [this](https://github.com/RabahX/YT-ReVanced-Module/releases/download/v18.07.35/YT-Module-ReVanced.zip) .

**Comment by ThePrimalPea** [comment]
It's fixed.
